# Generated by Django 3.2.7 on 2023-10-26 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('dietary_restrictions', models.CharField(max_length=255)),
                ('emergency_contact', models.CharField(max_length=255)),
                ('travel_style_preferences', models.CharField(max_length=255)),
                ('preferred_airlines', models.CharField(max_length=255)),
                ('budget_constraints', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferred_travel_dates', models.DateField()),
                ('trip_duration', models.IntegerField()),
                ('notification_preferences', models.CharField(blank=True, max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('profile_privacy', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
